Repository mishka-group/mishka_chelekom, pull requests merged in 2024-12, with the labels that each got.

#158 Chore: Modify colors of native select, add dark mode
  priv/templates/components/native_select.eex
  priv/templates/components/native_select.exs
Labels: Kind: Refactor, Level:CoreTeam

#159 Chore: Modify colors of range, add dark mode
  priv/templates/components/range_field.eex
  priv/templates/components/range_field.exs
Labels: Kind: Refactor, Level:CoreTeam

#160 Chore: Modify colors of toast, Add dark mode
  priv/templates/components/toast.eex
  priv/templates/components/toast.exs
Labels: Kind: Refactor, Level:CoreTeam

#161 Chore: Modify colors of list, add dark mode
  priv/templates/components/list.eex
  priv/templates/components/list.exs
Labels: Kind: Refactor, Level:CoreTeam

#162 Chore: Modify colors of fieldset, add dark mode
  priv/templates/components/fieldset.eex
  priv/templates/components/fieldset.exs
Labels: Kind: Refactor, Level:CoreTeam

#163 Chore: modify colors of files, add dark mode
  priv/templates/components/file_field.eex
  priv/templates/components/file_field.exs
Labels: Kind: Refactor, Level:CoreTeam

#164 Chore: Fix issues of colors and class names for form fields
  priv/templates/components/date_time_field.eex
  priv/templates/components/email_field.eex
  priv/templates/components/password_field.eex
  priv/templates/components/search_field.eex
  priv/templates/components/tel_field.eex
  priv/templates/components/text_field.eex
  priv/templates/components/textarea_field.eex
  priv/templates/components/url_field.eex
Labels: Kind: Refactor, Level:CoreTeam

#165 Chore: Modify colors of stepper, add dark mode
  priv/templates/components/stepper.eex
  priv/templates/components/stepper.exs
Labels: Kind: Refactor, Level:CoreTeam

#166 Chore: Modify colors of accordion, add dark mode
  priv/templates/components/accordion.eex
  priv/templates/components/accordion.exs
Labels: Kind: Refactor, Level:CoreTeam

#168 Chore: Modify colors of pagination, add dark mode
  priv/templates/components/pagination.eex
  priv/templates/components/pagination.exs
Labels: Kind: Refactor, Level:CoreTeam

#171 Feat: add filter props to image component
  priv/templates/components/image.eex
Labels: Kind:Enhancement, Level:Person

#172 Feat: Add other line styles to timeline
  priv/templates/components/timeline.eex
Labels: Kind:Suggestion, Kind: Refactor, Level:Person

#173 Feat: Add loader to slot to button component
  priv/templates/components/button.eex
Labels: Kind:Enhancement, Level:Person

#174 Feat: Add radius to toggle component
  priv/templates/components/toggle_field.eex
Labels: Kind: Refactor, Level:Person

#175 Feat: add space based on sizes to pagination component
  priv/templates/components/pagination.eex
Labels: Kind: Refactor, Level:Person

#176 Feat: add label slot to each chunk of progress
  mix.exs
  mix.lock
  priv/templates/components/progress.eex
  priv/templates/components/progress.exs
Labels: Kind: Refactor, Level:Person

#178 Feat: add separated variant to table
  CHANGELOG.md
  mix.exs
  priv/templates/components/table.eex
  priv/templates/components/table.exs
Labels: Kind: Refactor, Level:Person

#183 Chore: Remove `space-y-0` classes from Menu, Footer, Navbar, Tooltip components
  CHANGELOG.md
  priv/templates/components/footer.eex
  priv/templates/components/menu.eex
  priv/templates/components/navbar.eex
  priv/templates/components/tooltip.eex
Labels: Kind: Refactor, Level:Person

#185 Refactor: Fix issue of zooming inputs
  CHANGELOG.md
  priv/templates/components/date_time_field.eex
  priv/templates/components/email_field.eex
  priv/templates/components/number_field.eex
  priv/templates/components/password_field.eex
  priv/templates/components/search_field.eex
  priv/templates/components/tel_field.eex
  priv/templates/components/text_field.eex
  priv/templates/components/textarea_field.eex
  priv/templates/components/url_field.eex
Labels: Kind: Refactor, Level:Person

#189 Chore: Modify structure of popover and dropdown components
  CHANGELOG.md
  priv/templates/components/dropdown.eex
  priv/templates/components/navbar.eex
  priv/templates/components/popover.eex
Labels: Kind: Refactor, Level:Person

#194 Refactor: Stop spinner when an image is in done
  CHANGELOG.md
  lib/mix/tasks/mishka.ui.gen.component.ex
  priv/templates/components/file_field.eex
Labels: Kind:Suggestion, Kind: Refactor, Level:Person

#192 Chore: modify styles of form fields, add `badge_position` prop to badge
  priv/templates/components/badge.eex
  priv/templates/components/date_time_field.eex
  priv/templates/components/email_field.eex
  priv/templates/components/native_select.eex
  priv/templates/components/number_field.eex
  priv/templates/components/password_field.eex
  priv/templates/components/range_field.eex
  priv/templates/components/search_field.eex
  priv/templates/components/tel_field.eex
  priv/templates/components/text_field.eex
  priv/templates/components/textarea_field.eex
  priv/templates/components/url_field.eex
Labels: Kind: Refactor, Level:Person

#193 Chore: Modify card and overlay components styles
  priv/templates/components/card.eex
  priv/templates/components/overlay.eex
Labels: Kind: Refactor, Level:Person

#195 Chore: Modify table content component
  priv/templates/components/table_content.eex
Labels: Kind: Refactor, Level:Person

#196 Feat: Add variant to stepper, add loading state to stepper
  priv/templates/components/spinner.eex
  priv/templates/components/stepper.eex
  priv/templates/components/stepper.exs
Labels: Kind: Refactor, Level:Person

#197 Feat: add hoverable prop to list
  priv/templates/components/list.eex
Labels: Kind: Refactor, Level:Person

#198 Chore: add missing info to Navbar component's document
  priv/templates/components/navbar.eex
Labels: Kind:Documentation, Level:Person

#200 Feat: add base color and variant to card component
  priv/templates/components/card.eex
  priv/templates/components/card.exs
Labels: Kind: Refactor, Level:Person

#205 Feat: Add base color & variant to Sidebar
  priv/templates/components/sidebar.eex
  priv/templates/components/sidebar.exs
Labels: Kind: Refactor, Level:Person

#208 Feat: Add base color and variant to avatar
  priv/templates/components/avatar.eex
  priv/templates/components/avatar.exs
Labels: Kind: Refactor, Level:Person

#209 Feat: add base color variant of badge
  priv/templates/components/badge.eex
  priv/templates/components/badge.exs
Labels: Kind: Refactor, Level:Person

#210 Feat: add base color and variant to banner
  priv/templates/components/banner.eex
  priv/templates/components/banner.exs
Labels: Kind: Refactor, Level:Person

#211 feat: add base color variant to blockquote
  priv/templates/components/blockquote.eex
  priv/templates/components/blockquote.exs
Labels: Kind: Refactor, Level:Person

#212 Feat: add breadcrumb base color
  priv/templates/components/breadcrumb.eex
  priv/templates/components/breadcrumb.exs
Labels: Kind: Refactor, Level:Person

#213 Feat: add base color variant to button
  priv/templates/components/button.eex
  priv/templates/components/button.exs
Labels: Kind: Refactor, Level:Person

#214 Feat: add base color to carousel
  priv/templates/components/carousel.eex
  priv/templates/components/carousel.exs
Labels: Kind: Refactor, Level:Person

#215 Feat: add base color to device mockup
  priv/templates/components/device_mockup.eex
  priv/templates/components/device_mockup.exs
Labels: Kind: Refactor, Level:Person

#216 Feat: add color base to divider
  priv/templates/components/divider.eex
  priv/templates/components/divider.exs
Labels: Kind: Refactor, Level:Person

#218 Feat: add base color and variant to dropdown
  priv/templates/components/dropdown.eex
  priv/templates/components/dropdown.exs
Labels: Kind: Refactor, Level:Person

#220 Feat: add pagination base color
  priv/templates/components/pagination.eex
  priv/templates/components/pagination.exs
Labels: Kind: Refactor, Level:Person

#221 Feat: add accordion base color and variants
  priv/templates/components/accordion.eex
  priv/templates/components/accordion.exs
  priv/templates/components/list.eex
  priv/templates/components/list.exs
Labels: Kind: Refactor, Level:Person

#222 Feat: add base color & variant to tabs
  priv/templates/components/tabs.eex
  priv/templates/components/tabs.exs
Labels: Kind: Refactor, Level:Person

#223 Feat: add base color variant to table contnet
  priv/templates/components/table_content.eex
  priv/templates/components/table_content.exs
Labels: Kind: Refactor, Level:Person

#224 Feat: add base color to timeline
  priv/templates/components/timeline.eex
  priv/templates/components/timeline.exs
Labels: Kind: Refactor, Level:Person

#225 Feat: add base color and variant to toast
  priv/templates/components/toast.eex
  priv/templates/components/toast.exs
Labels: Kind: Refactor, Level:Person

#226 Feat: add base color and variant to tooltip
  priv/templates/components/tooltip.eex
  priv/templates/components/tooltip.exs
Labels: Kind: Refactor, Level:Person

#227 Feat: add base color to video
  priv/templates/components/video.eex
Labels: Kind: Refactor, Level:Person

#228 Feat: add base color to typography
  priv/templates/components/typography.eex
  priv/templates/components/typography.exs
Labels: Kind: Refactor, Level:Person

#229 Feat: add base color variant to table
  priv/templates/components/table.eex
  priv/templates/components/table.exs
Labels: Kind: Refactor, Level:Person

#230 Feat: add base color to stepper
  priv/templates/components/stepper.eex
  priv/templates/components/stepper.exs
Labels: Kind: Refactor, Level:Person

#231 Feat: add base color variant to speed dial
  priv/templates/components/speed_dial.eex
  priv/templates/components/speed_dial.exs
Labels: Kind: Refactor, Level:Person

#232 Feat: add base color to spinner
  priv/templates/components/spinner.eex
  priv/templates/components/spinner.exs
Labels: Kind: Refactor, Level:Person

#233 Feat: add base color to skeleton
  priv/templates/components/skeleton.eex
  priv/templates/components/skeleton.exs
Labels: Kind: Refactor, Level:Person

#234 Feat: add base color to rating
  priv/templates/components/rating.eex
  priv/templates/components/rating.exs
Labels: Kind: Refactor, Level:Person

#235 Feat: add base color and variant to progress
  priv/templates/components/progress.eex
  priv/templates/components/progress.exs
Labels: Kind: Refactor, Level:Person

#236 Feat: add base color and variant to popover
  priv/templates/components/popover.eex
  priv/templates/components/popover.exs
Labels: Kind: Refactor, Level:Person

#238 Feat: add base color and variant to navbar
  priv/templates/components/navbar.eex
  priv/templates/components/navbar.exs
Labels: Kind: Refactor, Level:Person

#239 Feat: add base color & variant to modal
  priv/templates/components/modal.eex
  priv/templates/components/modal.exs
Labels: Kind: Refactor, Level:Person

#240 Feat: add base color & prop to mega menu
  priv/templates/components/mega_menu.eex
  priv/templates/components/mega_menu.exs
Labels: Kind: Refactor, Level:Person

#241 Feat: add base color and variant to keyboard
  priv/templates/components/keyboard.eex
  priv/templates/components/keyboard.exs
Labels: Kind: Refactor, Level:Person

#242 Feat: add base color and variant to jumbotron
  priv/templates/components/jumbotron.eex
  priv/templates/components/jumbotron.exs
Labels: Kind: Refactor, Level:Person

#243 Feat: add base color to indicator
  priv/templates/components/indicator.eex
  priv/templates/components/indicator.exs
Labels: Kind: Refactor, Level:Person

#244 Feat: add base color and variant to form fields
  priv/templates/components/checkbox_field.eex
  priv/templates/components/checkbox_field.exs
  priv/templates/components/color_field.eex
  priv/templates/components/color_field.exs
  priv/templates/components/date_time_field.eex
  priv/templates/components/date_time_field.exs
  priv/templates/components/email_field.eex
  priv/templates/components/email_field.exs
  priv/templates/components/fieldset.eex
  priv/templates/components/fieldset.exs
  priv/templates/components/file_field.eex
  priv/templates/components/file_field.exs
  priv/templates/components/form_wrapper.eex
  priv/templates/components/form_wrapper.exs
  priv/templates/components/input_field.eex
  priv/templates/components/native_select.eex
  priv/templates/components/native_select.exs
  priv/templates/components/number_field.eex
  priv/templates/components/number_field.exs
  priv/templates/components/password_field.eex
  priv/templates/components/password_field.exs
  priv/templates/components/radio_field.eex
  priv/templates/components/radio_field.exs
  priv/templates/components/range_field.eex
  priv/templates/components/range_field.exs
  priv/templates/components/search_field.eex
  priv/templates/components/search_field.exs
  priv/templates/components/tel_field.eex
  priv/templates/components/tel_field.exs
  priv/templates/components/text_field.eex
  priv/templates/components/text_field.exs
  priv/templates/components/textarea_field.eex
  priv/templates/components/textarea_field.exs
  priv/templates/components/toggle_field.eex
  priv/templates/components/toggle_field.exs
  priv/templates/components/url_field.eex
  priv/templates/components/url_field.exs
Labels: Kind: Refactor, Level:Person
