Repository mishka-group/mishka_chelekom, pull requests merged in 2024-11, with the labels that each got.

#84 Revision and fix some missing part of some fields (version 0.0.1)
  mix.exs
  mix.lock
  priv/templates/components/checkbox_field.eex
  priv/templates/components/checkbox_field.exs
  priv/templates/components/color_field.eex
  priv/templates/components/date_time_field.eex
  priv/templates/components/fieldset.eex
  priv/templates/components/file_field.eex
  priv/templates/components/native_select.eex
  priv/templates/components/number_field.eex
  priv/templates/components/password_field.eex
  priv/templates/components/radio_field.eex
  priv/templates/components/radio_field.exs
  priv/templates/components/range_field.eex
  priv/templates/components/search_field.eex
  priv/templates/components/tel_field.eex
  priv/templates/components/text_field.eex
  priv/templates/components/textarea_field.eex
  priv/templates/components/toggle_field.eex
  priv/templates/components/toggle_field.exs
  priv/templates/components/url_field.eex
Labels: Kind:Bug, Kind:Documentation

#89 Enhancement - Modify colors of button component, add dark mode, fix issues of gradient variants
  priv/templates/components/button.eex
  priv/templates/components/button.exs
Labels: Kind:Enhancement, Kind: Refactor

#91 Enhancement - Add dark mode and fix issues of gradient variants of button component
  CHANGELOG.md
  README.md
  priv/templates/components/button.eex
  priv/templates/components/button.exs
Labels: Kind:Enhancement, Kind: Refactor, Level:CoreTeam

#92 Cli 0.0.2 community version (beta)
  .github/FUNDING.yml
  README.md
  lib/mix/tasks/mishka.ui.add.ex
  lib/mix/tasks/mishka.ui.gen.components.ex
  mix.exs
  mix.lock
Labels: Kind:Enhancement, Level:Person

#93 Cli 0.0.2 supports helpers import
  lib/mix/tasks/mishka.ui.add.ex
  lib/mix/tasks/mishka.ui.gen.component.ex
  lib/mix/tasks/mishka.ui.gen.components.ex
Labels: Kind:Enhancement

#94 chore: update Badge component styles, and modified colors
  priv/templates/components/badge.eex
  priv/templates/components/badge.exs
  priv/templates/components/button.eex
Labels: Kind: Refactor, Level:CoreTeam

#98 chore: update Avatar colors and add dark mode support
  CHANGELOG.md
  priv/templates/components/avatar.eex
  priv/templates/components/avatar.exs
Labels: Kind: Refactor, Level:CoreTeam

#99 Chore: Modify Alert component colors and add dark mode
  CHANGELOG.md
  priv/templates/components/alert.eex
  priv/templates/components/alert.exs
Labels: Kind: Refactor, Level:CoreTeam

#100 Chore: Modify colors of spinner, Add dark mode
  CHANGELOG.md
  priv/templates/components/spinner.eex
  priv/templates/components/spinner.exs
Labels: Kind: Refactor, Level:CoreTeam

#102 Chore: Modify colors and dark mode of breadcrumb
  CHANGELOG.md
  priv/templates/components/breadcrumb.eex
  priv/templates/components/breadcrumb.exs
Labels: Kind: Refactor, Level:CoreTeam

#103 Chore: Change colors and add dark mode of blockquote
  CHANGELOG.md
  priv/templates/components/blockquote.eex
  priv/templates/components/blockquote.exs
Labels: Kind: Refactor, Level:CoreTeam

#104 Chore: Modify colors, variants and add dark mode to dropdown
  CHANGELOG.md
  priv/templates/components/dropdown.eex
  priv/templates/components/dropdown.exs
Labels: Kind: Refactor, Level:CoreTeam

#106 Chore: Change colors of overlays , add dark mode
  CHANGELOG.md
  priv/templates/components/overlay.eex
  priv/templates/components/overlay.exs
Labels: Kind: Refactor, Level:CoreTeam

#107 Chore: Change colors of card and add dark mode
  CHANGELOG.md
  priv/templates/components/card.eex
  priv/templates/components/card.exs
Labels: Kind: Refactor, Level:CoreTeam

#108 Feat: Add new variant and colors to card component
  priv/templates/components/card.eex
  priv/templates/components/card.exs
Labels: Kind: Refactor, Level:Person

#109 Feat: Add gradient and bordered variants to banner
  priv/templates/components/banner.eex
  priv/templates/components/banner.exs
Labels: Kind: Refactor, Level:CoreTeam

#111 Feat: Add `gradient` and `bordered` variants
  priv/templates/components/alert.eex
  priv/templates/components/alert.exs
Labels: Kind: Refactor, Level:CoreTeam

#113 Feat: Add `dark` and `white` to spinner
  priv/templates/components/spinner.eex
  priv/templates/components/spinner.exs
Labels: Kind: Refactor, Level:CoreTeam

#114 Feat: add `white` and `dark` to divider
  priv/templates/components/divider.eex
  priv/templates/components/divider.exs
Labels: Kind: Refactor, Level:CoreTeam

#115 Feat: Add `gradient` and `bordered` variants
  priv/templates/components/drawer.eex
  priv/templates/components/drawer.exs
Labels: Kind: Refactor, Level:CoreTeam

#118 Feat: Add `bordered` gradient to button
  priv/templates/components/button.eex
  priv/templates/components/button.exs
Labels: Kind: Refactor, Level:CoreTeam

#119 Feat: Add gradient to dropdown component
  priv/templates/components/dropdown.eex
  priv/templates/components/dropdown.exs
Labels: Kind: Refactor, Level:CoreTeam

#120 Feat: add dark and white colors to bread crumb
  priv/templates/components/breadcrumb.eex
  priv/templates/components/breadcrumb.exs
Labels: Kind: Refactor, Level:CoreTeam

#121 Feat: Add `gradient` and `borderd` variants of `popover`
  CHANGELOG.md
  priv/templates/components/popover.eex
  priv/templates/components/popover.exs
Labels: Kind: Refactor, Level:CoreTeam

#122 Chore: Add new dark and white colors to overlay
  priv/templates/components/overlay.eex
  priv/templates/components/overlay.exs
Labels: Kind: Refactor, Level:CoreTeam

#123 Chore: Modify colors, Introduce dark mode to rating component
  CHANGELOG.md
  priv/templates/components/rating.eex
  priv/templates/components/rating.exs
Labels: Kind: Refactor, Level:CoreTeam

#125 Chore: Change colors, Introduce dark mode to chat component
  CHANGELOG.md
  priv/templates/components/chat.eex
  priv/templates/components/chat.exs
Labels: Kind: Refactor, Level:CoreTeam

#126 Feat: add gradient variant, change colors, add dark mode
  CHANGELOG.md
  priv/templates/components/modal.eex
  priv/templates/components/modal.exs
Labels: Kind: Refactor, Level:CoreTeam

#127 Chore: Modify colors of keyboard and add dark mode
  CHANGELOG.md
  priv/templates/components/keyboard.eex
  priv/templates/components/keyboard.exs
Labels: Kind: Refactor, Level:CoreTeam

#128 Chore: Modify colors of jumbotron, add dark mode to component
  CHANGELOG.md
  priv/templates/components/jumbotron.eex
  priv/templates/components/jumbotron.exs
Labels: Kind: Refactor, Level:CoreTeam

#129 Chore: change colors of indicator, add dark mode
  CHANGELOG.md
  priv/templates/components/indicator.eex
  priv/templates/components/indicator.exs
Labels: Kind: Refactor, Level:CoreTeam

#130 Chore: Modify colors of carousel, Add dark mode
  CHANGELOG.md
  priv/templates/components/carousel.eex
  priv/templates/components/carousel.exs
Labels: Kind: Refactor, Level:CoreTeam

#132 Chore: Modify colors of footer, add dark mode
  CHANGELOG.md
  priv/templates/components/footer.eex
  priv/templates/components/footer.exs
Labels: Kind: Refactor, Level:CoreTeam

#133 Chore: Modify colors, add dark mode of MegaMenu
  CHANGELOG.md
  priv/templates/components/mega_menu.eex
  priv/templates/components/mega_menu.exs
Labels: Kind: Refactor, Level:CoreTeam

#134 Chore: Modify navbar colors, add dark mode of navbar component
  CHANGELOG.md
  priv/templates/components/navbar.eex
  priv/templates/components/navbar.exs
Labels: Kind: Refactor, Level:CoreTeam

#138 Chore: Modify colors of text, email, url, search, number, password, textarea, tel fields of form
  CHANGELOG.md
  priv/templates/components/email_field.eex
  priv/templates/components/email_field.exs
  priv/templates/components/number_field.eex
  priv/templates/components/number_field.exs
  priv/templates/components/password_field.eex
  priv/templates/components/password_field.exs
  priv/templates/components/search_field.eex
  priv/templates/components/search_field.exs
  priv/templates/components/tel_field.eex
  priv/templates/components/tel_field.exs
  priv/templates/components/text_field.eex
  priv/templates/components/text_field.exs
  priv/templates/components/textarea_field.eex
  priv/templates/components/textarea_field.exs
  priv/templates/components/url_field.eex
  priv/templates/components/url_field.exs
Labels: Kind: Refactor, Level:CoreTeam

#140 Chore: Change form wrapper colors, add dark mode
  CHANGELOG.md
  priv/templates/components/form_wrapper.eex
  priv/templates/components/form_wrapper.exs
Labels: Kind: Refactor, Level:CoreTeam

#141 Chore: Change colors of gradient of progress
  priv/templates/components/progress.eex
Labels: Kind: Refactor, Level:Person

#143 Chore: Modify colors of radio field component of forms
  CHANGELOG.md
  priv/templates/components/radio_field.eex
  priv/templates/components/radio_field.exs
Labels: Kind: Refactor, Level:CoreTeam

#145 Chore: Change colors of sidebar, add dark mode
  CHANGELOG.md
  priv/templates/components/sidebar.eex
  priv/templates/components/sidebar.exs
Labels: Kind: Refactor, Level:CoreTeam

#147 Chore: Add new variants, modify colors of tooltip
  priv/templates/components/tooltip.eex
  priv/templates/components/tooltip.exs
Labels: Kind: Refactor, Level:CoreTeam

#149 Chore: Modify colors, add dark mode typography
  priv/templates/components/typography.eex
  priv/templates/components/typography.exs
Labels: Kind: Refactor, Level:CoreTeam

#150 Chore: Modify colors of toggle, add dark mode
  priv/templates/components/toggle_field.eex
  priv/templates/components/toggle_field.exs
Labels: Kind: Refactor, Level:CoreTeam

#152 Chore: Modify colors of skeleton, add dark mode
  priv/templates/components/skeleton.eex
  priv/templates/components/skeleton.exs
Labels: Kind: Refactor, Level:CoreTeam

#153 Chore: Modify colors of table content and add dark mode
  priv/templates/components/table_content.eex
  priv/templates/components/table_content.exs
Labels: Kind: Refactor, Level:CoreTeam

#154 Chore: Modify timeline colors, add dark mode
  priv/templates/components/timeline.eex
  priv/templates/components/timeline.exs
Labels: Kind: Refactor, Level:CoreTeam

#155 Chore: modify colors of table, add dark mode
  CHANGELOG.md
  mix.exs
  priv/templates/components/table.eex
  priv/templates/components/table.exs
Labels: Kind: Refactor, Level:CoreTeam

#156 Chore: Modify colors of tabs, add dark mode
  CHANGELOG.md
  priv/templates/components/tabs.eex
  priv/templates/components/tabs.exs
Labels: Kind: Refactor, Level:CoreTeam
