Repository mishka-group/mishka_chelekom, pull requests merged in 2025-03, with the labels that each got.

#312 Fix some Phoenix CoreComponent backward compatibility issues for Ash
  CHANGELOG.md
  mix.exs
  mix.lock
  priv/components/input_field.eex
  priv/components/input_field.exs
  priv/components/modal.eex
  priv/components/modal.exs
Labels: Kind:Bug, Kind: Refactor, Level:CoreTeam

#313 Fix missing ids in table and Flash `assign_new` to create new id from pattern
  CHANGELOG.md
  mix.exs
  mix.lock
  priv/components/alert.eex
  priv/components/table.eex
Labels: Kind:Bug, Level:Person

#314 Refactor: Fix scrollarea scrollbar visibility issue
  priv/assets/js/scrollArea.js
  priv/components/scroll_area.eex
Labels: Kind:Bug, Level:Person

#317 Use more generous dependency on igniter
  lib/mix/tasks/mishka.ui.gen.component.ex
  lib/mix/tasks/mishka.ui.gen.components.ex
  mix.exs
  priv/components/input_field.eex
Labels: Kind:Suggestion, Kind: Refactor, Level:Person

#321 Feat: Add combobox component
  CHANGELOG.md
  mix.exs
  priv/assets/js/combobox.js
  priv/assets/js/scrollArea.js
  priv/components/checkbox_card.eex
  priv/components/checkbox_field.eex
  priv/components/combobox.eex
  priv/components/combobox.exs
  priv/components/divider.eex
  priv/components/menu.eex
  priv/components/native_select.eex
  priv/components/radio_card.eex
  priv/components/scroll_area.eex
Labels: Kind:Enhancement, Level:CoreTeam

#322 Chore: Skipping Color in the Base Variant
  priv/components/accordion.eex
  priv/components/alert.eex
  priv/components/badge.eex
  priv/components/banner.eex
  priv/components/blockquote.eex
  priv/components/button.eex
  priv/components/card.eex
  priv/components/chat.eex
  priv/components/date_time_field.eex
  priv/components/drawer.eex
  priv/components/dropdown.eex
  priv/components/email_field.eex
  priv/components/fieldset.eex
  priv/components/file_field.eex
  priv/components/footer.eex
  priv/components/form_wrapper.eex
  priv/components/jumbotron.eex
  priv/components/keyboard.eex
  priv/components/list.eex
  priv/components/mega_menu.eex
  priv/components/modal.eex
  priv/components/native_select.eex
  priv/components/navbar.eex
  priv/components/number_field.eex
  priv/components/pagination.eex
  priv/components/password_field.eex
  priv/components/popover.eex
  priv/components/progress.eex
  priv/components/search_field.eex
  priv/components/sidebar.eex
  priv/components/speed_dial.eex
  priv/components/stepper.eex
  priv/components/table.eex
  priv/components/table_content.eex
  priv/components/tabs.eex
  priv/components/tel_field.eex
  priv/components/text_field.eex
  priv/components/textarea_field.eex
  priv/components/toast.eex
  priv/components/tooltip.eex
  priv/components/url_field.eex
Labels: Kind: Refactor, Level:Person

#323 Refactor: Change selected option in combobox component
  priv/assets/js/combobox.js
  priv/components/combobox.eex
  priv/components/combobox.exs
Labels: Kind: Refactor, Level:CoreTeam

#324 Refactor: Fix color of radio and checkbox fields
  priv/components/checkbox_field.eex
  priv/components/radio_field.eex
Labels: Kind: Refactor, Level:Person

#325 Update Readme for version 0.0.4
  CHANGELOG.md
  README.md
  mix.exs
  mix.lock
Labels: Kind:Documentation

#328 Refactor: Fix Dropdown Bugs and Enhance Dynamic Behavior
  priv/assets/js/floating.js
  priv/components/dropdown.eex
  priv/components/dropdown.exs
Labels: Kind:Bug, Kind: Refactor, Level:Person

#329 Refactor: add conditional styling to divider and buttons
  priv/components/button.eex
  priv/components/divider.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#330 Feat: add layouts flex and grid components
  CHANGELOG.md
  mix.exs
  mix.lock
  priv/components/layout.eex
  priv/components/layout.exs
Labels: Kind:Enhancement, Level:Person
