Repository mishka-group/mishka_chelekom, pull requests merged in 2025-05, with the labels that each got.

#403 fix: outdated link
  README.md
Labels: Kind:Documentation, Level:Person

#413 Add install version of `mishka.assets.deps` mix command
  .gitignore
  CHANGELOG.md
  lib/mix/tasks/mishka.assets.deps.ex
  lib/mix/tasks/mishka.assets.install.ex
  mix.exs
  mix.lock
Labels: Kind:Enhancement

#414 Add remove JS package for `mix mishka.assets.deps` cli
  CHANGELOG.md
  lib/mix/tasks/mishka.assets.deps.ex
  lib/mix/tasks/mishka.assets.install.ex
Labels: Kind:Enhancement, Level:Person
