Repository mishka-group/mishka_chelekom, pull requests merged in 2025-01, with the labels that each got.

#251 Fix: Fix `wrapper_width` issue of tooltip
  priv/templates/components/tooltip.eex
Labels: Kind:Bug, Level:Person

#252 Refactor: Fix issues of accordion, add new props
  priv/templates/components/accordion.eex
Labels: Kind: Refactor, Level:Person

#253 Refactor: Fix issues and add new props to Card, Avatar, Badge and Button
  priv/templates/components/avatar.eex
  priv/templates/components/badge.eex
  priv/templates/components/button.eex
  priv/templates/components/card.eex
Labels: Kind: Refactor, Level:Person

#256 Add export task for Community cli and fix some issues of converting
  CHANGELOG.md
  lib/mix/tasks/mishka.ui.add.ex
  lib/mix/tasks/mishka.ui.export.ex
  lib/mix/tasks/mishka.ui.gen.component.ex
Labels: Kind:Bug, Kind:Enhancement, Level:Person

#258 Refactor: add new prop to card media
  priv/components/card.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#259 Refactor: change chat section styles
  priv/components/chat.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#260 Refactor: add and remove unnecessary classes from date field
  priv/components/date_time_field.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#261 Refactor: add and remove unnecessary classes from email field
  priv/components/email_field.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#262 Refactor: fix style issues of fieldset
  priv/components/fieldset.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#263 Refactor: Add new props and fix color issues, remove extra functions from list
  priv/components/list.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#264 Refactor: fix issues of shadow in native select
  priv/components/native_select.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#265 Refactor: add and remove unnecessary classes number field
  priv/components/number_field.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#266 Refactor: fix issues of password field
  priv/components/password_field.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#267 Refactor: change structure of popover
  priv/components/popover.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#269 Refactor: add line height class to rating button
  priv/components/rating.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#270 Refactor: add and remove unnecessary classes of search
  priv/components/search_field.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#272 Refactor: add new variants to table
  priv/components/table.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#274 Refactor: add and remove unnecessary classes tel field
  priv/components/tel_field.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#275 Refactor: add and remove unnecessary classes text field
  priv/components/text_field.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#276 Refactor: add and remove unnecessary classes textarea field
  priv/components/textarea_field.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#277 Refactor: change structure of tooltip
  priv/components/tooltip.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#273 Refactor: add new styles to tabs
  priv/components/tabs.eex
  priv/components/tabs.exs
Labels: Kind:Bug, Kind: Refactor, Level:Person

#257 Refactor: add classes to badge
  priv/components/badge.eex
Labels: Kind:Bug, Kind: Refactor, Level:Person

#278 Refactor: change styles of url field
  priv/components/url_field.eex
Labels: Kind: Refactor, Level:Person

#282 Chore: add and remove properties from `exs` files of components
  priv/components/accordion.exs
  priv/components/alert.exs
  priv/components/button.eex
  priv/components/card.exs
  priv/components/chat.exs
  priv/components/date_time_field.exs
  priv/components/email_field.exs
  priv/components/fieldset.exs
  priv/components/file_field.exs
  priv/components/footer.exs
  priv/components/mega_menu.exs
  priv/components/modal.exs
  priv/components/native_select.exs
  priv/components/number_field.exs
  priv/components/password_field.exs
  priv/components/popover.exs
  priv/components/radio_field.exs
  priv/components/search_field.exs
  priv/components/speed_dial.exs
  priv/components/table.exs
  priv/components/table_content.exs
  priv/components/tel_field.exs
  priv/components/text_field.exs
  priv/components/textarea_field.exs
  priv/components/tooltip.exs
  priv/components/url_field.exs
  priv/components/video.exs
Labels: Kind: Refactor, Level:CoreTeam

#280 Setting up version 0.0.2
  README.md
  mix.exs
  priv/components/typography.eex
Labels: Kind:Documentation

#284 Chore: Add panel class attribute to tab components
  priv/components/tabs.eex
Labels: Kind:Bug, Level:Person

#285 Update Igniter for fixing windows issues
  lib/mix/tasks/mishka.ui.gen.component.ex
  lib/mix/tasks/mishka_chelekom.install.ex
  mix.exs
  mix.lock
Labels: Kind:Bug, Kind: Refactor, Level:Person

#287 Chore: add paddings and width fit to alert
  mix.exs
  mix.lock
  priv/components/alert.eex
  priv/components/alert.exs
Labels: Kind: Refactor, Level:Person

#288 Feat: add badge to tab component
  priv/components/list.eex
  priv/components/tabs.eex
  priv/components/tabs.exs
Labels: Kind: Refactor, Level:Person

#291 Add rest attribute for stepper_section
  priv/components/stepper.eex
Labels: Kind: Refactor, Level:Person
