Repository mishka-group/mishka_chelekom, pull requests merged in 2025-02, with the labels that each got.

#294 add missing slot to gallery component
  priv/components/gallery.eex
Labels: Kind:Bug

#295 chore: fix typo in tab, checkbox field, radio field components
  README.md
  mix.exs
  priv/components/checkbox_field.eex
  priv/components/gallery.eex
  priv/components/radio_field.eex
  priv/components/tabs.eex
Labels: Kind: Refactor, Level:Person

#296 Feat: add scroll area component & added missing features of Phoenix core components
  CHANGELOG.md
  lib/mix/tasks/mishka.ui.gen.component.ex
  mix.exs
  mix.lock
  priv/assets/js/scrollArea.js
  priv/components/alert.eex
  priv/components/button.eex
  priv/components/button.exs
  priv/components/form_wrapper.eex
  priv/components/form_wrapper.exs
  priv/components/icon.eex
  priv/components/icon.exs
  priv/components/list.eex
  priv/components/navbar.eex
  priv/components/navbar.exs
  priv/components/scroll_area.eex
  priv/components/scroll_area.exs
  priv/components/table.eex
Labels: Kind:Enhancement, Kind:Suggestion, Level:CoreTeam

#300 Refactor: refactor `scroll_area` component
  CHANGELOG.md
  mix.exs
  mix.lock
  priv/assets/js/scrollArea.js
  priv/components/scroll_area.eex
Labels: Kind:Bug, Kind:Enhancement

#302 Fix: keep scrollbar visible during thumb dragging
  mix.exs
  mix.lock
  priv/assets/js/scrollArea.js
  priv/components/scroll_area.eex
Labels: Kind:Bug

#303 Fix: fix issue of scroll area direction styles
  priv/components/scroll_area.eex
Labels: Kind:Bug

#304 feat(ui): add global components installing support and JS formatter
  CHANGELOG.md
  lib/mix/tasks/mishka.ui.gen.component.ex
  lib/mix/tasks/mishka.ui.gen.components.ex
  lib/mix/tasks/mishka_chelekom.install.ex
  mix.exs
  mix.lock
Labels: Kind:Enhancement, Level:Person

#305 Feat: add radio card component
  CHANGELOG.md
  mix.exs
  priv/components/form_wrapper.eex
  priv/components/radio_card.eex
  priv/components/radio_card.exs
  priv/components/radio_field.eex
Labels: Kind:Enhancement, Level:Person
